export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUESTS_ROBOTS_PENDING = "REQUESTS_ROBOTS_PENDING";
export const REQUESTS_ROBOTS_SUCESS = "REQUESTS_ROBOTS_SUCESS";
export const REQUESTS_ROBOTS_FAILED = "REQUESTS_ROBOTS_FAILED";
